version: "3.9"

services:
  passwords-generator-web:
    build:
      dockerfile: Dockerfile
      context: ./
    restart: on-failure
    volumes:
      - .:/passwords-generator-web
    expose:
      - "3000"
    ports:
      - "3000:3000"
